version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: "10m"
    max-file: "5"
  driver: json-file

services:
  api:
    image: cluelessapi
    build:
      context: ./src
      dockerfile: Dockerfile
    hostname: src
    restart: always
    logging: *default-logging